/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HeartGame.GUI_Game;

import HeartGame.CODE.MyConnCheck;
import HeartGame.CODE.RandomGenarate;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Thulani Wickramasinghe
 */
public class LogIn extends javax.swing.JFrame {

    //public variables
    public static int player;
    public static String uname;
    public static String id;
    public static String email;

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();

        //center the form
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        buttonlogin = new javax.swing.JButton();
        buttonback = new javax.swing.JButton();
        pwdfield = new javax.swing.JPasswordField();
        buttonreset = new javax.swing.JButton();
        lblpwforgot = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HeartGame - 2022");
        setMinimumSize(new java.awt.Dimension(940, 585));

        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(940, 585));
        jPanel1.setMinimumSize(new java.awt.Dimension(940, 585));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 36)); // NOI18N
        jLabel1.setText("HEART GAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 274, 50);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Forte", 1, 27)); // NOI18N
        jLabel2.setText("SIGN IN");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(200, 40, 121, 38);

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel3.setText("UserName");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 120, 97, 21);

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(65, 191, 90, 22);

        txtusername.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel2.add(txtusername);
        txtusername.setBounds(220, 115, 197, 40);

        buttonlogin.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        buttonlogin.setText("LOG IN");
        buttonlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonloginActionPerformed(evt);
            }
        });
        jPanel2.add(buttonlogin);
        buttonlogin.setBounds(60, 270, 103, 40);

        buttonback.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        buttonback.setText("BACK");
        buttonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbackActionPerformed(evt);
            }
        });
        jPanel2.add(buttonback);
        buttonback.setBounds(340, 270, 91, 40);

        pwdfield.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel2.add(pwdfield);
        pwdfield.setBounds(220, 182, 200, 40);

        buttonreset.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        buttonreset.setText("RESET");
        buttonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonresetActionPerformed(evt);
            }
        });
        jPanel2.add(buttonreset);
        buttonreset.setBounds(200, 270, 110, 40);

        lblpwforgot.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblpwforgot.setText("Forgot password?");
        lblpwforgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpwforgotMouseClicked(evt);
            }
        });
        jPanel2.add(lblpwforgot);
        lblpwforgot.setBounds(200, 330, 130, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HeartGameImages/game.jpg"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(-190, -20, 750, 410);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(220, 120, 530, 390);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HeartGameImages/sii.jpg"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(940, 585));
        jLabel5.setMinimumSize(new java.awt.Dimension(940, 585));
        jLabel5.setPreferredSize(new java.awt.Dimension(940, 585));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 940, 780);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonloginActionPerformed
        // store the username to a public variable
        uname = txtusername.getText();

        //get the player id to a public variable by the username given by the player
        try {
            PreparedStatement st;
            String query1 = "SELECT `playerID` FROM `players` WHERE `username` LIKE '" + uname + "' ";
            st = MyConnCheck.getConnection().prepareStatement(query1);
            ResultSet result = st.executeQuery();
            if (result.next()) {

                id = result.getString("playerID");
                player = Integer.parseInt(id);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        PreparedStatement st;
        ResultSet rs;

        String pass = String.valueOf(pwdfield.getPassword());

        String query = "SELECT  * FROM `players` WHERE `username` = ? AND `password`= ? ";

        try {
            st = MyConnCheck.getConnection().prepareStatement(query);

            st.setString(1, uname);
            st.setString(2, pass);

            rs = st.executeQuery();

            RandomGenarate.player(player);
            RandomGenarate.username(uname);

            //check the user credential to check the user is a player or an admin
            if (rs.next()) {
                if ((!uname.equals("admin")) && (!pass.equals("admin"))) {
                    PlayUI play = new PlayUI();
                    play.setVisible(true);
                    play.pack();
                    play.setLocationRelativeTo(null);
                    play.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    PlayUI.txtwelcome.setText("WELCOME " + uname + " !!!");
                    this.dispose();
                } else {
                    Admin admin = new Admin();
                    admin.setVisible(true);
                    admin.pack();
                    admin.setLocationRelativeTo(null);
                    admin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect Username or Password", "Login Failed", 2);
            }

        } catch (SQLException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_buttonloginActionPerformed


    private void buttonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbackActionPerformed
        //goto the main userinterface
        MainUI main = new MainUI();
        main.setVisible(true);
        main.pack();
        main.setLocationRelativeTo(null);
        main.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_buttonbackActionPerformed

    private void buttonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonresetActionPerformed
        //reset the fields
        pwdfield.setText("");
        txtusername.setText("");
    }//GEN-LAST:event_buttonresetActionPerformed

    //MOUSE CLICKED EVENT
    private void lblpwforgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpwforgotMouseClicked
        //goto the forgetpassword interface
        ForgotPassword pwd = new ForgotPassword();
        pwd.setVisible(true);
        pwd.pack();
        pwd.setLocationRelativeTo(null);
        pwd.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pwd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblpwforgotMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonback;
    private javax.swing.JButton buttonlogin;
    private javax.swing.JButton buttonreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel lblpwforgot;
    private javax.swing.JPasswordField pwdfield;
    public static javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
