/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HeartGame.GUI_Game;

import HeartGame.CODE.RandomGenarate;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;

/**
 *
 * @author Thulani Wickramasinghe
 */
public class PlayUI extends javax.swing.JFrame {

    public PlayUI() {
        initComponents();

        //center the form
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtwelcome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnplay = new javax.swing.JButton();
        buttonlogout = new javax.swing.JButton();
        buttonhelp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HeartGame - 2022");
        setMaximumSize(new java.awt.Dimension(726, 447));
        setMinimumSize(new java.awt.Dimension(726, 447));

        jPanel1.setMaximumSize(new java.awt.Dimension(726, 447));
        jPanel1.setMinimumSize(new java.awt.Dimension(726, 447));
        jPanel1.setPreferredSize(new java.awt.Dimension(726, 447));
        jPanel1.setLayout(null);

        txtwelcome.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jPanel1.add(txtwelcome);
        txtwelcome.setBounds(50, 100, 620, 120);

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 1, 36)); // NOI18N
        jLabel3.setText("HEART GAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 20, 274, 50);

        btnplay.setFont(new java.awt.Font("Jokerman", 1, 30)); // NOI18N
        btnplay.setText("PLAY");
        btnplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplayActionPerformed(evt);
            }
        });
        jPanel1.add(btnplay);
        btnplay.setBounds(230, 270, 240, 70);

        buttonlogout.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        buttonlogout.setText("LOGOUT");
        buttonlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(buttonlogout);
        buttonlogout.setBounds(590, 380, 120, 40);

        buttonhelp.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        buttonhelp.setText("HELP");
        buttonhelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonhelpActionPerformed(evt);
            }
        });
        jPanel1.add(buttonhelp);
        buttonhelp.setBounds(590, 320, 120, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HeartGameImages/reg1.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -20, 730, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplayActionPerformed
        //start the timer by this method
        RandomGenarate.startTimer(50);
        //start to genarate random game levels UI
        try {
            RandomGenarate.getRandom();
        } catch (SQLException ex) {
            Logger.getLogger(PlayUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnplayActionPerformed

    private void buttonlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonlogoutActionPerformed
        //goto the main UI
        MainUI main = new MainUI();
        main.setVisible(true);
        main.pack();
        main.setLocationRelativeTo(null);
        main.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_buttonlogoutActionPerformed

    //EVENT-ACTION
    private void buttonhelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonhelpActionPerformed
        /**
         *text to voice assistance
         * 
         * 
         * @author Sarmila Sivaraja
         */

        //Text to voice assistance is used in here
        //external plugings - freetts
        String vs = "Welcome to Our Heart Game, In this game, you have to complete 10 levels in 50 seconds. We wish you good luck! Thank you. ";

        //objects of the Voice class and voice manager
        //OOP concepts
        Voice voiceclass;
        VoiceManager vm = VoiceManager.getInstance();
        
        //choose the male voice as Kevin
        voiceclass = vm.getVoice("kevin");

        voiceclass.allocate();
        voiceclass.speak(vs);
    }//GEN-LAST:event_buttonhelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnplay;
    private javax.swing.JButton buttonhelp;
    private javax.swing.JButton buttonlogout;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel txtwelcome;
    // End of variables declaration//GEN-END:variables
}
