/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HeartGame.GUI_Game;

import javax.swing.JFrame;

/**
 *
 * @author Thulani Wickramasinghe
 */
public class Ranking extends javax.swing.JFrame {

    /**
     * Creates new form Ranking
     */
    public Ranking() {
        initComponents();

        //center the form
        this.setLocationRelativeTo(null);
    }

    //public vaariables
    public static String title1;
    public static String text1;
    public static String user1;

    //to show the Result of the player in ResultUI interface
    //Result UI, using public variables store the data and send by creating methods and assigning the data to the Ranking UI , variables.
    public static void User1(String title) {
        title1 = title;
    }

    public static void User(String text) {
        text1 = text;
    }

    public static void username(String user) {
        user1 = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnreplay = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableD = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HeartGame - 2022");
        setMinimumSize(new java.awt.Dimension(726, 447));

        jPanel1.setMaximumSize(new java.awt.Dimension(726, 447));
        jPanel1.setMinimumSize(new java.awt.Dimension(726, 447));
        jPanel1.setPreferredSize(new java.awt.Dimension(726, 447));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 1, 36)); // NOI18N
        jLabel3.setText("HEART GAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 20, 274, 50);

        jLabel2.setFont(new java.awt.Font("Poor Richard", 1, 26)); // NOI18N
        jLabel2.setText("SCOREBOARD");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 90, 180, 30);

        btnreplay.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        btnreplay.setText("REPLAY");
        btnreplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreplayActionPerformed(evt);
            }
        });
        jPanel1.add(btnreplay);
        btnreplay.setBounds(550, 180, 120, 50);

        btnback.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback);
        btnback.setBounds(550, 270, 120, 50);

        jScrollPane2.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N

        tableD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableD.setFont(new java.awt.Font("MV Boli", 0, 20)); // NOI18N
        tableD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLAYER", "SCORE"
            }
        ));
        tableD.setGridColor(new java.awt.Color(255, 255, 255));
        tableD.setRowHeight(20);
        jScrollPane2.setViewportView(tableD);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(190, 140, 310, 230);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HeartGameImages/reg1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnreplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreplayActionPerformed
        //replay the game by goto the playUI, UI
        PlayUI pl = new PlayUI();
        pl.setVisible(true);
        pl.pack();
        pl.setLocationRelativeTo(null);
        pl.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        PlayUI.txtwelcome.setText("WELCOME " + user1 + " !!!");
        this.dispose();
    }//GEN-LAST:event_btnreplayActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        //view the result of your game by going back
        Result rs = new Result();
        rs.setVisible(true);
        rs.pack();
        rs.setLocationRelativeTo(null);
        Result.lblresult.setText(title1);
        Result.result.setText(text1);
        rs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ranking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnreplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tableD;
    // End of variables declaration//GEN-END:variables
}
