package HeartGame.GUI_Game;

import HeartGame.CODE.MyConnCheck;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Thulani Wickramasinghe
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public SignUp() {
        initComponents();

        //center the form
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtpassword1 = new javax.swing.JPasswordField();
        txtpassword = new javax.swing.JPasswordField();
        btnreset = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HeartGame - 2022");
        setMinimumSize(new java.awt.Dimension(940, 585));

        jPanel1.setMaximumSize(new java.awt.Dimension(940, 585));
        jPanel1.setMinimumSize(new java.awt.Dimension(940, 585));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 36)); // NOI18N
        jLabel1.setText("HEART GAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 274, 50);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Forte", 1, 27)); // NOI18N
        jLabel2.setText("SIGN UP");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(240, 30, 116, 38);

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel3.setText("UserName");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(70, 150, 100, 22);

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel4.setText("Email");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(90, 100, 60, 22);

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel5.setText("Re-Password");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 250, 120, 22);

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel7.setText("Password");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(70, 200, 90, 22);

        txtemail.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txtemail.setPreferredSize(new java.awt.Dimension(6, 28));
        jPanel2.add(txtemail);
        txtemail.setBounds(190, 90, 310, 40);

        txtusername.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txtusername.setPreferredSize(new java.awt.Dimension(6, 28));
        jPanel2.add(txtusername);
        txtusername.setBounds(190, 140, 310, 40);

        txtpassword1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel2.add(txtpassword1);
        txtpassword1.setBounds(190, 240, 310, 40);

        txtpassword.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel2.add(txtpassword);
        txtpassword.setBounds(190, 190, 310, 40);

        btnreset.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        btnreset.setText("RESET");
        btnreset.setPreferredSize(new java.awt.Dimension(90, 40));
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel2.add(btnreset);
        btnreset.setBounds(250, 320, 104, 40);

        btnback.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        btnback.setText("BACK");
        btnback.setPreferredSize(new java.awt.Dimension(90, 40));
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel2.add(btnback);
        btnback.setBounds(410, 320, 104, 40);

        btnsubmit.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        btnsubmit.setText("SUBMIT");
        btnsubmit.setPreferredSize(new java.awt.Dimension(90, 40));
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel2.add(btnsubmit);
        btnsubmit.setBounds(80, 320, 104, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HeartGameImages/game.jpg"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(-140, 0, 730, 410);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(200, 110, 580, 410);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HeartGameImages/sii.jpg"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(940, 585));
        jLabel6.setMinimumSize(new java.awt.Dimension(940, 585));
        jLabel6.setPreferredSize(new java.awt.Dimension(940, 585));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 940, 780);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed

        //get data and store it in variables
        String email = txtemail.getText();
        String uname = txtusername.getText();
        String pass = String.valueOf(txtpassword.getPassword());
        String pass1 = String.valueOf(txtpassword1.getPassword());

        //check the empty fields
        if (email.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Your Email", "Empty Field", 2);
        } else if (uname.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter A Username", "Empty Field", 2);
        } else if (pass.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter A Password", "Empty Field", 2);
        } else if (pass1.equals("")) {
            JOptionPane.showMessageDialog(null, "Re-Enter A Password", "Empty Field", 2);
        } //check the entered passwords are matching
        else if (!pass.equals(pass1)) {
            JOptionPane.showMessageDialog(null, "Password Doesn't Match!", "Confirm Password", 2);
        } //check the username is already taken or not
        else if (checkUsername(uname)) {
            JOptionPane.showMessageDialog(null, "This Username Is Already Taken!", "Username Failed", 2);
        } //check the email is already taken or not
        else if (checkEmail(email)) {
            JOptionPane.showMessageDialog(null, "This Email Is Already Taken!", "Email Failed", 2);

            //insert a new user to the database
        } else {

            PreparedStatement st;
            String query = "INSERT INTO `players`(`username`, `password`, `email`) VALUES (?,?,?)";

            try {
                st = MyConnCheck.getConnection().prepareStatement(query);

                st.setString(1, uname);
                st.setString(2, pass);
                st.setString(3, email);

                if (st.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this, "New Player Added!");
                    LogIn log = new LogIn();
                    log.setVisible(true);
                    log.pack();
                    log.setLocationRelativeTo(null);
                    log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }

            } catch (SQLException ex) {
                Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    //function to check if the username already exist
    public boolean checkUsername(String username) {
        PreparedStatement st;
        ResultSet rs;
        boolean checkUser = false;
        String query = "SELECT  * FROM `players` WHERE `username` = ?";
        try {
            st = MyConnCheck.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();

            if (rs.next()) {
                checkUser = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return checkUser;
    }

    //function to check if the email  already exist
    public boolean checkEmail(String email) {
        PreparedStatement st;
        ResultSet rs;
        boolean checkMail = false;
        String query = "SELECT  * FROM `players` WHERE `email` = ?";
        try {
            st = MyConnCheck.getConnection().prepareStatement(query);
            st.setString(1, email);
            rs = st.executeQuery();

            if (rs.next()) {
                checkMail = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        return checkMail;
    }


    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        //goto the main UI
        MainUI main = new MainUI();
        main.setVisible(true);
        main.pack();
        main.setLocationRelativeTo(null);
        main.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        //reset the fields
        txtemail.setText("");
        txtusername.setText("");
        txtpassword.setText("");
        txtpassword1.setText("");
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JPasswordField txtpassword1;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
